# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: ec09f73
_src_path: gh:scipp/copier_template
description: Polarization data reduction for the European Spallation Source
max_python: '3.11'
min_python: '3.9'
namespace_package: ess
nightly_deps: scipp,sciline,scippnexus
orgname: scipp
prettyname: Esspolarization
projectname: esspolarization
related_projects: Scipp,Sciline,ScippNexus
year: 2023
