package:
  name: esspolarization

  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

requirements:
  build:
    - setuptools
    - setuptools_scm
  run:
    - dask
    - python>=3.9
    - python-graphviz
    - sciline>=23.12.0
    - scipp>=23.8.0
    - scippnexus>=23.11.0

test:
  imports:
    - esspolarization
  requires:
    - pytest
  source_files:
    - pyproject.toml
    - tests/
  commands:
    - python -m pytest tests

build:
  noarch: python
  script:
    - python -m pip install .

about:
  home: https://github.com/scipp/esspolarization
  license: BSD-3-Clause
  summary: Polarization data reduction for the European Spallation Source
  description: Polarization data reduction for the European Spallation Source
  dev_url: https://github.com/scipp/esspolarization
  doc_url: https://scipp.github.io/esspolarization
